# Generated by Django 4.2.4 on 2023-08-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter', '0005_rename_time_exercise_time_hour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeatType',
        ),
    ]
