# Generated by Django 4.2.4 on 2023-08-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calory_counter", "0006_delete_meattype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=1000000)),
                ("portion", models.PositiveIntegerField(default=1)),
                ("calorie", models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
