# Generated by Django 4.2.4 on 2023-08-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calory_counter", "0007_receipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="img_url",
            field=models.TextField(blank=True),
        ),
    ]
