# Generated by Django 4.2.4 on 2023-08-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter', '0008_receipe_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('difficult', 'difficult')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='receipe',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='time',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
    ]
