# Generated by Django 4.2.4 on 2023-08-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calory_counter", "0010_alter_receipe_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="ingredients",
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
