# Generated by Django 4.2.4 on 2023-09-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calory_counter", "0014_food_recipe_alter_receipe_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="food_sel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calory_counter.food",
            ),
        ),
    ]
