# Generated by Django 4.2.4 on 2023-09-05 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calory_counter", "0017_remove_food_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="person_of",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
