# Generated by Django 4.2.4 on 2023-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_water',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_water',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
