# Generated by Django 4.2.4 on 2023-08-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calory_counter", "0006_delete_meattype"),
        ("user", "0003_alter_profile_current_water"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calorie_exercise",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="exercises_selected",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calory_counter.exercise",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="time_hour_exercise",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name="PostExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calorie_amount", models.FloatField(blank=True, default=0, null=True)),
                ("time", models.IntegerField(blank=True, default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calory_counter.exercise",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
    ]
