# Generated by Django 4.2.4 on 2023-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter', '0016_remove_receipe_food_sel'),
        ('user', '0006_profile_total_calorie_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='calory_counter.receipe'),
        ),
    ]
