# Generated by Django 4.2.4 on 2023-09-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calory_counter", "0018_receipe_person_of"),
        ("user", "0008_remove_profile_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="recipe_selected",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calory_counter.receipe",
            ),
        ),
        migrations.AlterField(
            model_name="postfood",
            name="amount",
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name="PostRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calorie_amount", models.FloatField(blank=True, default=0, null=True)),
                ("amount", models.FloatField(default=1)),
                ("meat_type", models.CharField(max_length=50)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calory_counter.receipe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="all_recipe_selected_today",
            field=models.ManyToManyField(
                related_name="inventory",
                through="user.PostRecipe",
                to="calory_counter.receipe",
            ),
        ),
    ]
