# Generated by Django 4.2.4 on 2023-09-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calory_counter", "0018_receipe_person_of"),
        ("user", "0009_profile_recipe_selected_alter_postfood_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postfood",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calory_counter.receipe",
            ),
        ),
        migrations.AlterField(
            model_name="postfood",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calory_counter.food",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="all_recipe_selected_today",
            field=models.ManyToManyField(
                related_name="inventory",
                through="user.PostFood",
                to="calory_counter.receipe",
            ),
        ),
    ]
